== In-memory queue interface
Software and IOMMU interact using 3 in-memory queue data structures. 

* A command-queue (CQ) used by software to queue commands to the IOMMU.

* A fault/event queue (FQ) used by IOMMU to bring faults and events to 
  software attention..

* A page-request queue (PQ) used by IOMMU to report “Page Request” messages 
  received from PCIe devices connected to the IOMMU. This queue is supported 
  if the IOMMU supports PCIe ATS specification.

.IOMMU in-memory queues
["ditaa",shadows=false, separation=false]
....
            +---+---+--------------------------------+---+----+
  +-------->|.. | . |       Command Queue            | . | .. |
  |         +---+---+--------------------------------+---+----+
  |           ^                                        ^
+-+-+         |                                        |
|CQB|         |                                        |
+---+         |                                        |
|CQH+---------+                                        |
+---+                                                  |
|CQT+--------------------------------------------------+
+---+       +---+---+--------------------------------+---+----+
  +-------->|.. | . |       Fault Queue              | . | .. |
  |         +---+---+--------------------------------+---+----+
  |           ^                                        ^
+-+-+         |                                        |
|FQB|         |                                        |
+---+         |                                        |
|FQH+---------+                                        |
+---+                                                  |
|FQT+--------------------------------------------------+
+---+       +---+---+--------------------------------+---+----+
  +-------->|.. | . |       Page Request Queue       | . | .. |
  |         +---+---+--------------------------------+---+----+
  |           ^                                        ^
+-+-+         |                                        |
|PQB|         |                                        |
+---+         |                                        |
|PQH+---------+                                        |
+---+                                                  |
|PQT+--------------------------------------------------+
+---+
....
Each queue is a circular buffer with a head controlled by the consumer of data
in the queue and a tail controlled by the producer of data into the queue.
IOMMU is the producer of records into PQ and FQ and controls the tail register.
IOMMU is the consumer of commands produced by software into the CQ and controls
the head register. 

A queue is empty if the head is equal to the tail. A queue is full if the tail
is one minus the head. The head and tail wrap around when they reach the end of
the circular buffer.

The producer of data must ensure that the data written to queue memory and the
tail update are ordered such that the consumer that observes an update to the 
tail register must also observe all data produced into the queue between the 
offsets determined by the head and the tail. 

[NOTE]
====
All RISC-V IOMMU implementations are required to support in-memory queues 
located in main memory. Supporting in-memory queues in I/O memory not required.
====


=== Command-Queue (CQ)

Command  queue is used by software to queue commands to be executed by the 
IOMMU.

The PPN of the base of this in-memory queue and the size of the queue is 
configured into a memory-mapped register called command-queue base (cqb).

The tail of the command-queue resides in a software controlled read/write 
memory-mapped register called command-queue tail (cqt). The cqt is an index 
into the next command queue entry that software will write. Subsequent to 
writing the command(s), software advances the cqt by the count of the number 
of commands written. 

The head of the command-queue resides in a read-only memory-mapped IOMMU 
controlled register called command-queue head (cqh). The cqh is an index 
into the command that IOMMU should process next. Subsequent to processing 
each command IOMMU advances the cqh by 1. If cqh == cqt, the command-queue 
is empty. If cqt == (cqh - 1) the command-queue is full.

IOMMU commands are grouped into a major command group determined by the opcode
and within each group the func3 field specifies the function invoked by that 
command. The opcode defines format of the operand fields. One or more of those
fields may be used by the specific function invoked.

.Format of an IOMMU command

[wavedrom, , ]
....
{reg: [
  {bits: 7, name: 'opcode'},
  {bits: 3, name: 'func3'},
  {bits: 118, name: 'operands'},
], config:{lanes: 2, hspace:1024}}
....

==== IOMMU Page-Table cache invalidation commands

[wavedrom, , ]
....
{reg: [
  {bits: 7, name: 'opcode', attr: 'IOTINVAL(0x1)'},
  {bits: 3, name: 'func3',  attr: ['VMA-0x0', 'GVMA-0x1']},
  {bits: 1, name: 'PSCV'},
  {bits: 1, name: 'AV'},
  {bits: 1, name: 'GV'},
  {bits: 3, name: 'rsvd'},
  {bits: 20, name: 'PSCID'},
  {bits: 4, name: 'rsvd'},
  {bits: 16, name: 'GSCID'},
  {bits: 8, name: 'rsvd'},
  {bits: 52, name: 'ADDR[63:12]'},
], config:{lanes: 4, hspace:1024, fontsize:12}}
....

IOMMU operations cause implicit reads and writes to PDT, first-stage and 
second-stage page tables; however these implicit references are ordinarily not
ordered with respect to explicit load and stores to these data structures by 
the RISC-V hart in the machine. 

The IOMMU translation-table cache invalidation commands, IOTINVAL.VMA and 
IOTINVAL.GVMA synchronize updates to in-memory first-stage and second-stage 
page table data structures with the operation of the IOMMU and flush the 
matching IOATC entries.

The GV operand indicates if the guest Soft-context ID (GSCID) operand is valid.
The PSCV operand indicates if the process soft-context ID (PSCID) operand is 
valid. Setting PSCV to 1 is valid only with IOTINVAL.VMA. The AV operand indicates if the address (ADDR) operand is valid. When GV is 0, the translations 
associated with the host i.e. those where the second-stage translation is not 
active are operated on.

IOTINVAL.VMA guarantees that previous stores made to the first-stage page 
tables by the harts are observed before all subsequent implicit reads from 
IOMMU to the corresponding first-stage page tables.

.Table IOTINVAL.VMA operands and operations
[width=75%]
[%header, cols="3,3,20"]
|===
| AV   | PSCV   | Operation
| 0    | 0      | When GV=1, invalidates cached information from any level of 
                  the first-stage page table, for all VM address spaces 
                  associated with GSCID. 
                  When GV=0, invalidates cached information from any level of 
                  the first-stage page table, for all host address spaces.
| 0    | 1      | When GV=1, invalidates cached information from  any level of
                  the first-stage page tables, but only for the VM address 
                  space identified by PSCID and GSCID operand. Accesses to 
                  global mappings are not ordered. 
                  When GV=0, synchronizes updates any level of the first-stage
                  page tables, but only for the host address space identified 
                  by PSCID operand. Accesses to global mappings are not 
                  ordered. 
| 1    | 0      | When GV=1, invalidates cached information from  leaf 
                  first-stage page table entries corresponding to the IOVA in 
                  ADDR, for all VM address spaces associated with the GSCID 
                  operand.
                  When GV=0, invalidates cached information from leaf 
                  first-stage page table entries corresponding to the IOVA in 
                  ADDR, for all host address spaces.
| 1    | 1      | When GV=1, invalidates cached information from leaf 
                  first-stage page table entries corresponding to the IOVA in 
                  ADDR, for the VM address space identified by PSCID and GSCID
                  operand. Global mappings are not invalidated.
                  When GV=0, invalidates cached information from leaf 
                  first-stage page table entries corresponding to the IOVA in 
                  ADDR, for the host address space identified by PSCID operand.
                  Global mappings are not invalidated.
|===

IOTINVAL.GVMA guarantees that previous stores made to the second-stage page 
tables are observed before all subsequent implicit reads from IOMMU to the 
corresponding second-stage page tables. Setting PSCV to 1 with IOTINVAL.GVMA
is illegal.

.Table IOTINVAL.GVMA operands and operations
[width=75%]
[%header, cols="3,3,20"]
|===
| AV   | GV     | Operation
| n/a  | 0      | Invalidates cached information from  any level of the 
                  second-stage page table, for all VM address spaces.
| 0    | 1      | Invalidates cached information from any level of the 
                  second-stage page tables, but only for all VM address spaces
                  identified by the GSCID operand.
| 1    | 1      | Invalidates cached information from leaf second-stage page 
                  table entries corresponding to the guest-physical-address in
                  ADDR operand, for the all VM address spaces identified 
                  GSCID operand.
|===

[NOTE]
====
Implementations that cache VA to PA translations may ignore the 
guest-physical-address in ADDR operand of IOTINVAL.GVMA, when valid, and 
perform an invalidation of all virtual-addresses in VM address spaces 
identified by the GSCID operand if valid or all host address spaces if the 
GSCID operand is not valid.

Simpler implementations may ignore the operand of IOTINVAL.VMA and/or 
IOTINVAL.GVMA and always perform a global invalidation across all address 
spaces.
====

==== IOMMU directory cache commands

[wavedrom, , ]
....
{reg: [
  {bits: 7, name: 'opcode', attr: 'IODIR(0x2)'},
  {bits: 3, name: 'func3',  attr: ['INVAL_DDT-0x0', 'INVAL_PDT-0x1']},
  {bits: 1, name: 'DV'},
  {bits: 5, name: 'rsvd'},
  {bits: 20, name: 'PID'},
  {bits: 4, name: 'rsvd'},
  {bits: 16, name: 'DID'},
  {bits: 64, name: 'rsvd'},
], config:{lanes: 4, hspace:1024, fontsize:12}}
....

IOMMU operations cause implicit reads and writes to DDT and/or PDT; however 
these implicit references are ordinarily not ordered with respect to explicit 
load or store to DDT or PDT by the RISC-V harts in the machine. 

The IOMMU DDT cache invalidation command, IODIR.INVAL_DDT synchronize updates 
to DDT with the operation of the IOMMU and flush the matching cached entries.

The IOMMU PDT cache invalidation command, IODIR.INVAL_PDT synchronize updates 
to PDT with the operation of the IOMMU and flush the matching cached entries.

The DV operand indicates if the device ID (DID) operand is valid.

IODIR.INVAL_DDT guarantees that any previous stores made by a RISC-V hart to 
the DDT are observed before all subsequent implicit reads from IOMMU to DDT. 
If DV is 0, then the command invalidates all  DDT and PDT entries cached for 
all devices. If DV is 1, then the command invalidates cached leaf level DDT 
entry for the device identified by DID operand and all associated PDT entries.
The PID operand is reserved for IODIR.INVAL_DDT.

IODIR.INVA_PDT guarantees that any previous stores made by a RISC-V hart to 
the PDT are observed before all subsequent implicit reads from IOMMU to PDT. 
The command invalidates leaf PDT entry for the specified PID and DID. 

==== IOMMU Command-queue Fence commands

[wavedrom, , ]
....
{reg: [
  {bits: 7, name: 'opcode', attr: 'IOFENCE(0x3)'},
  {bits: 3, name: 'func3',  attr: 'C-0x0'},
  {bits: 1, name: 'PR'},
  {bits: 1, name: 'PW'},
  {bits: 1, name: 'AV'},
  {bits: 1, name: 'WIS'},
  {bits: 18, name: 'rsvd'},
  {bits: 32, name: 'DATA'},
  {bits: 2, name: 'rsvd'},
  {bits: 62, name: 'ADDR'},
], config:{lanes: 4, hspace:1024, fontsize:12}}
....
The IOMMU fetches commands from the CQ in order but the IOMMU may execute the 
fetched commands out of order. The IOMMU advancing cqh is not a guarantee that
 the commands fetched by the IOMMU have been executed or committed. 

A IOFENCE.C command guarantees that all previous commands fetched from the CQ 
have been completed and committed. 

The commands may be used to order memory accesses from I/O devices connected to
the IOMMU as viewed by the IOMMU, other RISC-V harts, and external devices or 
coprocessors. The PR and PW bits can be used to request that the IOMMU ensure 
that all previous requests from devices that have already been processed by the
IOMMU be committed to a global ordering point such that they can be observed by
all RISC-V harts and IOMMUs in the machine. 

The wired-interrupt-signaling (WIS) bit when set to 1 causes a wired-interrupt
from the command queue to be generated on completion of IOFENCE.C. This bit is
reserved if the IOMMU supports MSI.

[NOTE]
====
Software should ensure that all previous read and writes processed by the IOMMU
have been committed to a global ordering point before reclaiming memory made 
accessible to a device. A safe sequence for such memory reclamation is to first
update the page tables to disallow access to the memory from the device and 
then use the IOTINVAL.VMA or IOTINVAL.GVMA appropriately to synchronize the 
IOMMU with the update to the page table. As part of the synchronization if the
memory reclaimed was previously made read accessible to the device then request
ordering of all previous reads; else if the memory reclaimed was previously 
made write accessible to the device then request ordering of all previous 
reads and writes to the IOFENCE. Ordering previous reads may be required if 
the reclaimed memory will be used to hold data that must not be made visible 
to the device.

The ordering guarantees are made for accesses to main-memory. For accesses to 
I/O memory, the ordering guarantees are implementation and I/O protocol 
defined.

Simpler implementations may unconditionally order all previous memory accesses
globally.
====

The AV command operand indicates if ADDR operand and DATA operands are valid. 
If AV=1, the IOMMU writes DATA to memory at a 4-byte aligned address in ADDR 
operand as a 4-byte store. 

[NOTE]
====
Software may configure the ADDR command operand to specify the address of the 
sereipnum_le/seteipnum_be in an IMSIC to cause an external interrupt 
notification on IOFENCE.C completion. Alternatively, software may program ADDR
to a memory location and use IOFENCE.C to set a flag in memory indicating 
command completion.
====

==== IOMMU MSI table cache invalidation  commands

[wavedrom, , ]
....
{reg: [
  {bits: 7, name: 'opcode', attr: 'IOTINVAL(0x1)'},
  {bits: 3, name: 'func3',  attr: ['MSI-0x2']},
  {bits: 1, name: 'PSCV'},
  {bits: 1, name: 'AV'},
  {bits: 1, name: 'GV'},
  {bits: 3, name: 'rsvd'},
  {bits: 20, name: 'PSCID'},
  {bits: 4, name: 'rsvd'},
  {bits: 16, name: 'GSCID'},
  {bits: 8, name: 'rsvd'},
  {bits: 52, name: 'ADDR[63:12]'},
], config:{lanes: 4, hspace:1024, fontsize:12}}
....

IOMMU operations cause implicit reads and writes to the MSI page table; however
these implicit references are ordinarily not ordered with respect to explicit 
loads or stores to these data structures by the RISC-V harts in the machine. 

IOTINVAL.MSI synchronizes updates to the MSI page table with the operation of 
the IOMMU and invalidates the matching cache entries.

The PSCV operand is reserved and must be 0 for IOTINVAL.MSI.

.Table IOTINVAL.MSI operands and operations
[width=75%]
[%header, cols="3,3,20"]
|===
| AV   | GV     | Operation
| 0    | 0      | Invalidates all cached MSI page table entries for host 
                  associated devices.
| 0    | 1      | Invalidates MSI page table entry identified by 
                  INT_FILE_NUM for host associated devices.
| 1    | 0      | Invalidates all cached MSI page table entries of VM 
                  identified by GSCID operand.
| 1    | 1      | Invalidates MSI page table entry identified by INT_FILE_NUM 
                  of VM identified by GSCID operand. 
|===

==== IOMMU ATS commands

[wavedrom, , ]
....
{reg: [
  {bits: 7, name: 'opcode', attr: 'ATS(0x4)'},
  {bits: 3, name: 'func3',  attr: ['INVAL-0x0', 'PRGR-0x1']},
  {bits: 1, name: 'DSV'},
  {bits: 1, name: 'PV'},
  {bits: 4, name: 'rsvd'},
  {bits: 20, name: 'PID'},
  {bits: 4, name: 'rsvd'},
  {bits: 8, name: 'DSEG'},
  {bits: 16, name: 'RID'},
  {bits: 64, name: 'PAYLOAD'},
], config:{lanes: 4, hspace:1024, fontsize:12}}
....
The ATS.INVAL command instructs the IOMMU to send a “Invalidation Request” 
message to the PCIe device function identified by RID. An 
“Invalidation Request” message is used to clear a specific subset of the 
address range from the address translation cache in a device function. The 
ATS.INVAL command completes when an “Invalidation Completion” response message
is received from the device or a protocol defined timeout occurs while waiting
for a response. The IOMMU may advance the cqh and fetch more commands from CQ 
while a response is awaited. 

[NOTE]
====
Software that needs to know if the invalidation operation completed on the 
device may use the IOMMU command-queue fence command (IOFENCE.C) to wait for 
the responses to all prior “Invalidation Request” messages. The IOFENCE.C is 
guaranteed to not complete before all previously fetched commands were executed
and completed. A previously fetched ATS command to invalidate device ATC does 
not complete till either the request times out or a valid response is received
from the device.
====

The ATS.PRGR command instructs the IOMMU to send a “Page Group Response” 
message to the PCIe device function identified by the RID. The 
“Page Group Response” message is used by system hardware and/or software to 
communicate with the device functions page-request interface to signal 
completion of a “Page Request”, or the catastrophic failure of the interface.

If the PV operand is set to 1, the message is generated with a PASID TLP 
prefix with the PASID field set to the PID operand. 

The PAYLOAD operand of the command is used to form the message body. 

If the DSV operand is 1, then a valid destination segment number is specified 
by the DSEG operand.


=== Fault/Event-Queue (FQ)
Fault/Event queue is an in-memory queue data structure used to report events 
and faults raised when processing transactions. Each fault record is 64 bytes.

The PPN of the base of this in-memory queue and the size of the queue is 
configured into a memory-mapped register called fault-queue base (fqb).

The tail of the fault-queue resides in a IOMMU controlled read-only 
memory-mapped register called fqt.  The fqt is an index into the next fault 
record that IOMMU will write in the fault-queue. Subsequent to writing the 
record, the IOMMU advances the fqt by 1. The head of the fault-queue resides 
in a read/write memory-mapped software controlled register called fqh. The fqh
is an index into the next fault record that SW should process next. Subsequent
to processing fault record(s) software advances the fqh by the count of the 
number of fault records processed. If fqh == fqt, the fault-queue is empty. If
fqt == (fqh - 1) the fault-queue is full.

.Fault-queue record
[wavedrom, , ]
....
{reg: [
  {bits: 24, name: 'DID'},
  {bits: 20, name: 'PID'},
  {bits:  1, name: 'PV'},
  {bits:  1, name: 'PRIV'},
  {bits:  6, name: 'TTYP'},
  {bits: 12, name: 'CAUSE'},
  {bits: 32, name: 'for custom use'},
  {bits: 32, name: 'reserved'},
  {bits: 64, name: 'iotval'},
  {bits: 64, name: 'iotval2'},
], config:{lanes: 8, hspace:1024, fontsize:12}}
....
The CAUSE is a code indicating the cause of the fault/event.










